### ISSUE TITLE
Problems in starting IPython locally

### ISSUE THREAD

**Issue by LucianaMarques** [alexmojaki/stack_data#6]
Hi there,

I occasionally contribute to IPython and I ran into the following issue:

```
$ python3 -m IPython
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/luciana.marques/dev/ipython/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/Users/luciana.marques/dev/ipython/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/luciana.marques/dev/ipython/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/Users/luciana.marques/dev/ipython/IPython/core/ultratb.py", line 99, in <module>
    import stack_data
ModuleNotFoundError: No module named 'stack_data'
```

I think it's because `stack_data` has became required in IPython, correct? I did not want to install the package locally at first, I wanted to find another solution regarding future releases, and having in mind we are facing [performance issues](https://github.com/ipython/ipython/issues/12191). Is there anything to be done right now?

I'm happy to submit a PR to fix it, I'm just struggling to find something that could work.

Thanks!

**Comment by alexmojaki** [comment]
`IPython` requires `stack_data`, therefore you have to install it. Not sure what there is to add to that. Logic that was in IPython was intentionally extracted into this package to improve the codebase, and this also adds new features and fixes.

`stack_data` is small, importing it doesn't take long. Try this code:

```python
from time import time
start = time()
import stack_data
elapsed = time() - start
print(elapsed)
```

On my machine that generally takes 0.02 seconds. It will take significantly less time if you put it in the context of IPython and most have the standard library has already been loaded.

In any case, this can only be considered a problem with IPython, not stack_data.
